export const projects = [
  {
    img: "http://127.0.0.1:5501/assets/img/work1.png",
    title: "IndiaMart Clone",
    des: "is an Indian massive open online Cosmetics Platform for Purchasing Indian Goods in Cheapest price.",
    demo: "",
    live: "https://realindiamart.netlify.app/",
    gitHub: "https://github.com/raus376/IndiaMart_Website",
    technologies: ["HTML", "CSS", "JavaScript", "Rest API"],
  },
  {
    img: "http://127.0.0.1:5501/assets/img/work9.png",
    title: "Meesho-clone",
    des: "Meesho is a social commerce platform that undertakes retail distribution, enabling small retail merchants to connect and sell their products effectively via social media channel",
    demo: "",
    live: "https://dreamy-douhua-212517.netlify.app/",
    gitHub: "https://github.com/Chadharyyogi/Meesho-Project",
    technologies: ["HTML", "CSS", "JavaScript", "Rest API"],
  },
  {
    img: "http://127.0.0.1:5501/assets/img/work2.png",
    title: "Unplash-Clone",
    des: "is an Indian massive open online tock photography for Purchasing Indian Goods in Cheapest price.",
    demo: "",
    live: "https://fluffy-basbousa-63859b.netlify.app/",
    gitHub: "https://fluffy-basbousa-63859b.netlify.app/	",
    technologies: ["React", "Redux", "HTML", "CSS", "JavaScript"],
  },

  //   {
  //     img: "https://user-images.githubusercontent.com/73213873/107113597-f547e200-6885-11eb-8abd-72106074907a.png",
  //     title: "Clone of Medium",
  //     des: "Clone of a blogging web application, Medium where a user can read the blogs written by others and show their response also, one can share their thoughts by posting a blog.",
  //     demo: "",
  //     live: "https://medium-web.netlify.app/",
  //     gitHub: "https://github.com/himrd95/Medium-Clone.git",
  //     technologies: ["React", "HTML", "CSS", "javaScript"],
  //   },
  //   {
  //     img: "https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966",
  //     title: "Clone of Fitness Blender",
  //     des: "This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.",
  //     demo: "",
  //     live: "https://anshusagar.github.io/FitnessBlender/",
  //     gitHub: "https://github.com/Anshusagar/FitnessBlender.git",
  //     technologies: ["HTML", "CSS", "javaScript"],
  //   },
  //   {
  //     img: "https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true",
  //     title: "Mailchimp Clone",
  //     des: "This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.",
  //     demo: "",
  //     live: "https://mandarsatam.github.io/Mailchimp-Clone/",
  //     gitHub: "https://github.com/mandarsatam/Mailchimp-Clone",
  //     technologies: ["HTML", "CSS", "javaScript"],
  //   },
];
