export const projects = [
  {
    img: "https://res.cloudinary.com/djjrzubcr/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1673791062/Hubspot-image_njahoc.jpg",
    title: "HubSpot-Clone",
    des: "HubSpot is a Cloud-Based CRM. HubSpot is a Software platform designed to help Company market and sell more effectively",
    demo: "",
    live: "https://animated-narwhal-cecc2b.netlify.app/",
    gitHub: "https://github.com/Guruprasad3n/HubSpot.com---Clone",
    technologies: [
      "JavaScript",
      "React",
      "Redux",
      "Node",
      "Express",
      "MongoDB",
    ],
  },
  {
    img: "https://res.cloudinary.com/djjrzubcr/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1673791148/Yoox-image_u3tsho.jpg",
    title: "Yoox-Clone",
    des: "Clone of fashion products E-commerce website. We have added Authentication functionality, added add to cart, along with checkout function.",
    demo: "",
    live: "https://smart-point.vercel.app/",
    gitHub: "https://github.com/shubhojeet1/cut-price-5327",
    technologies: [
      "JavaScript",
      "React",
      "Redux",
      "Node",
      "Express",
      "MongoDB",
    ],
  },
  {
    img: "https://res.cloudinary.com/dfjdtufsq/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1667716682/samples/work1_z3822l.jpg",
    title: "IndiaMart Clone",
    des: "is an Indian massive open online Cosmetics Platform for Purchasing Indian Goods in Cheapest price.",
    demo: "",
    live: "https://realindiamart.netlify.app/",
    gitHub: "https://github.com/raus376/IndiaMart_Website",
    technologies: ["REST API", "DOM", "HTML", "CSS", "javaScript"],
  },
];
